dataroot: "../data"
mediaroot: "media"
cart_backgrounds: '../data/backgrounds'
ncbasin: "hydroshed_csl03_gl_l021_sh300.nc"
nctws: "tws_sh.nc"
ncbasav: "ncbasav.nc"
ncp-et: "prec_evap_flux_new.nc"
ncp-et_comb: "era5_prec_evap_flux_storage.nc"
glofas-comb: "glofasv4_outlets_comb.nc"
dsdt: "dsdtbasav.nc"
geoslurpschema: "vidiegu25"
glofasdisloc: "glofasv4_discharge_locations.gpkg"
