dataroot: "../data"
ncbasin: "hydroshed_csl03_gl_l021_sh300.nc"
nctws: "tws_sh.nc"
ncbasav: "ncbasav.nc"
ncp-et: "prec_evap_flux.nc"
dsdt: "dsdtbasav.nc"
geoslurpschema: "vidiegu25"
glofasdisloc: "glofasv4_discharge_locations.gpkg"
